version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5433:5432"

  redis:
    image: redis:7.2.4
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    command: "redis-server --save 20 1 --loglevel warning"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # console port
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    command: server --console-address ":9001" /data


volumes:
  postgres_data:
  redis_data:
  minio_data: