version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=default
      - S3_ACCESS=admin
      - S3_SECRET=adminadmin
      - DATABASE_URL=postgresql://postgres:password@db:5432/app
      - REDIS_URL=redis://redis:6379
      - DOMAIN=http://localhost:8000
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - .:/src

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - "5433:5432"

  redis:
    image: redis:7.2.4
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    command: "redis-server --save 20 1 --loglevel warning"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # console port
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    command: server --console-address ":9001" /data


volumes:
  postgres_data:
  redis_data:
  minio_data: