SECONDS_IN_SECONDS = 1
MINUTES_IN_SECONDS = SECONDS_IN_SECONDS * 60
HOURS_IN_SECONDS = MINUTES_IN_SECONDS * 60
DAY_IN_SECONDS = HOURS_IN_SECONDS * 24

USDT_RUB_PRICE = 98.0
USDT_UZS_PRICE = 13500.0
STARS_USDT_PRICE = 0.013
