"""empty message

Revision ID: 1bcf7a7f4d38
Revises: d3dac6ef7832
Create Date: 2024-08-29 13:17:33.437934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcf7a7f4d38'
down_revision: Union[str, None] = 'd3dac6ef7832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('date_game', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True),
    sa.Column('course', sa.Float(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=True)
    op.add_column('users', sa.Column('balance_usdt', sa.Float(), server_default='0', nullable=False))
    op.alter_column('users', 'balance',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.drop_column('users', 'balance_usdt')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
