"""empty message

Revision ID: 280655224d26
Revises: 551e13208f0f
Create Date: 2024-08-30 07:05:18.952609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280655224d26'
down_revision: Union[str, None] = '551e13208f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_referrals',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_game_id', sa.BigInteger(), nullable=False),
    sa.Column('ref_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ref_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_game_id'], ['users_games_m2m.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_referrals_id'), 'users_referrals', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referrals_id'), table_name='users_referrals')
    op.drop_table('users_referrals')
    # ### end Alembic commands ###
