"""empty message

Revision ID: 551e13208f0f
Revises: 1bcf7a7f4d38
Create Date: 2024-08-29 13:59:56.219310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551e13208f0f'
down_revision: Union[str, None] = '1bcf7a7f4d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_games_m2m',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('total_rate', sa.Float(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('choose', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_games_m2m_id'), 'users_games_m2m', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_games_m2m_id'), table_name='users_games_m2m')
    op.drop_table('users_games_m2m')
    # ### end Alembic commands ###
