"""empty message

Revision ID: 673ddb2c23a2
Revises: 0b0aa1fefd7b
Create Date: 2024-09-26 10:23:26.422258

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '673ddb2c23a2'
down_revision: Union[str, None] = '0b0aa1fefd7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('logo_game_start_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logo_game_start_time')
    # ### end Alembic commands ###
