"""Create stars_payments table

Revision ID: 6cfafb8d6da8
Revises: 673ddb2c23a2
Create Date: 2024-10-01 14:19:23.571953

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6cfafb8d6da8'
down_revision: Union[str, None] = '673ddb2c23a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'stars_payments',
        sa.Column('id', sa.UUID(), primary_key=True),
        sa.Column('user_id', sa.BigInteger(), sa.ForeignKey('users.id', ondelete="NO ACTION"), nullable=False),
        sa.Column('total_amount', sa.Integer(), nullable=False),
        sa.Column('telegram_payment_charge_id', sa.String(), nullable=False),
        sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('time_updated', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stars_payments')
    # ### end Alembic commands ###
