"""empty message

Revision ID: 79a71f4993ff
Revises: 280655224d26
Create Date: 2024-08-30 07:19:58.835178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a71f4993ff'
down_revision: Union[str, None] = '280655224d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_referrals', 'user_game_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_referrals', 'user_game_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
