"""Update stars_payments table to match new model

Revision ID: 7c51c96565f5
Revises: 673ddb2c23a2
Create Date: 2024-10-03 15:41:19.154612

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c51c96565f5'
down_revision: Union[str, None] = '6cfafb8d6da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stars_payments', sa.Column('amount_stars', sa.Integer(), nullable=False))
    op.add_column('stars_payments', sa.Column('amount_usdt', sa.Float(), nullable=False))
    op.drop_column('stars_payments', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stars_payments', sa.Column('total_amount', sa.Integer(), nullable=False))
    op.drop_column('stars_payments', 'amount_usdt')
    op.drop_column('stars_payments', 'amount_stars')
    # ### end Alembic commands ###
