"""empty message

Revision ID: 8190b57a592e
Revises: 79a71f4993ff
Create Date: 2024-09-01 04:27:00.124616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8190b57a592e'
down_revision: Union[str, None] = '79a71f4993ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_computed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'is_computed')
    # ### end Alembic commands ###
