"""empty message

Revision ID: a02127e581d7
Revises: 1138a51f3f9d
Create Date: 2024-09-05 19:25:45.529081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02127e581d7'
down_revision: Union[str, None] = '1138a51f3f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('course_at_computed', sa.Float(), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'course_at_computed')
    # ### end Alembic commands ###
