"""empty message

Revision ID: f8471f2b10a0
Revises: a02127e581d7
Create Date: 2024-09-05 20:12:41.972026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8471f2b10a0'
down_revision: Union[str, None] = 'a02127e581d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_games_m2m', sa.Column('win_total_rate', sa.Float(), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_games_m2m', 'win_total_rate')
    # ### end Alembic commands ###
